name: flutter_desktop_context_menu
description: This plugin allows Flutter desktop apps to create native context menus.
version: 0.2.5
homepage: https://github.com/proteye/flutter_desktop_context_menu

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  dependency_validator: ^5.0.2

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterDesktopContextMenuPlugin
      macos:
        pluginClass: FlutterDesktopContextMenuPlugin
      windows:
        pluginClass: FlutterDesktopContextMenuPlugin
